### PR TITLE
Windows wheels

### PR DESCRIPTION
**Pull request by andreasxp**
Hello again. I saw #157 and nothing immediately jumped out at me as being amiss, so I tried to replicate the windows pipeline from simple actions. Apparently windows *does* build after all, though I'm not sure what is the difference between my pipeline and yours.

Would you be able to use this as a starting point to reopening and solving #156? I would be happy to assist further if necessary.

### CODE REVIEW

**Comment by asottile** [comment]
nah I don't think the bug is here. it's somewhere else

**Comment by andreasxp** [comment]
Just to clarify - I ran the github actions on my fork and the wheels DO build - check out https://github.com/andreasxp/dockerfile/actions/runs/5700227090

**Comment by asottile** [comment]
yeah to be clear I'm solving this a different way. the difference between the two is virtualenv

**Comment by andreasxp** [comment]
> yeah to be clear I'm solving this
Let me know if I understood you correctly - you're saying you are working on #156 after all?

**Comment by asottile** [comment]
yes but the problem is not here

**Pull request closed without merging**
